name: Demo Workflow

on:      #trigger
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:  
  VAR: 'This is global'
jobs:
    build:
      runs-on: ubuntu-latest    #one vm
      
      steps:
    #step1
        - name: checkout the repo
          uses: actions/checkout@v2